### ISSUE TITLE
如何设置某一段的速率（变速）呢？

### ISSUE THREAD

**Issue by onesmalldog** [CoderHenry66/WAVideoBox#10]
感谢您的分享！

demo中修改速率（变速）是整体修改，如何分开修改呢？看demo大概是使用这个函数
- (void)performWithAsset:(AVAsset *)asset models:(NSArray <WAAVSEGearboxCommandModel *> *)gearboxModels;

如果是这样，WAAVSEGearboxCommandModel 这个对象的参数应该如何传递呢？
感激不尽～

**Comment by CoderHenry66** [comment]
传一个WAAVSEGearboxCommandModel的数组就可以了。
比如工作区里的时长是4秒，
第一个model可以设，beganDuration:CMTimeZero，duration:CMTimeMake(1200,600),scale传2,代表是零到二秒，两倍变速
第二个model可以设，beganDurationCMTimeMake(1200,600)，duration:CMTimeMake(1200,600),scale传3,代表是二到四秒，三倍变速
则传两个model的数组就可以，注意数组内model之间的时间范围不要重叠
