### ISSUE TITLE
压缩微信小视频只有声音，没图像

### ISSUE THREAD

**Issue by hjljunli** [CoderHenry66/WAVideoBox#11]

**Comment by CoderHenry66** [comment]
测试了一下，没问题，上个代码看看呗

**Comment by CoderHenry66** [comment]
新版微信的视频矩阵为a = 0,b = 1,c = -1,d=0,旋转90度，但tx为0,导致视频旋转后x值为-width,正常的90度矩阵应该是tx=width，已做了矩阵校正

**Comment by Denial92** [comment]
270度时，旋转矩阵换成 CGAffineTransformMake(0, -1, 1, 0, 0 , natureSize.width);
