### ISSUE TITLE
可能存在某些视频无法裁剪，希望您有时间看下，麻烦您了

### ISSUE THREAD

**Issue by Matcha00** [CoderHenry66/WAVideoBox#14]
Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12780), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x600000c9c1b0 {Error Domain=NSOSStatusErrorDomain Code=-12780 "(null)"}}
错误信息，视频格式MP4，并且视屏经过微信后就能裁剪 ，希望可以讨论下

**Comment by CoderHenry66** [comment]
麻烦将视频发到287819129@qq.com，我看下

**Comment by Matcha00** [comment]
好的

**Comment by congWang-1015** [comment]
同/issues/19](url)， 希望作者有时间看一下呢。

**Comment by congWang-1015** [comment]
iOS13问题得到解决
