### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by jinxiaobing-maker** [CoderHenry66/WAVideoBox#20]
点击 合并+水印+旋转+... 按钮 崩溃  (我自己添加的视频 )  视频链接http://pic.iyoufou.com/2CDF41EB-D762-4B52-B744-99159A16AD84/L0/001201910211032557202.mp4

2019-10-21 10:27:34.733467+0800 WAVideoBox[2578:206414] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'This method does not support multi-video processing for the time being.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23ba9f68 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff25614de9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   WAVideoBox                          0x000000010f362de4 -[WAAVSERotateCommand performWithAsset:degress:] + 660
	5   WAVideoBox                          0x000000010f3699c6 __35-[WAVideoBox rotateVideoByDegress:]_block_invoke + 518
	6   libdispatch.dylib                   0x000000010f6a3df8 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x000000010f6a4d6c _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010f6ab613 _dispatch_lane_serial_drain + 788
	9   libdispatch.dylib                   0x000000010f6ac1a3 _dispatch_lane_invoke + 422
	10  libdispatch.dylib                   0x000000010f6b7a64 _dispatch_workloop_worker_thread + 719
	11  libsystem_pthread.dylib             0x00007fff518cd611 _pthread_wqthread + 421
	12  libsystem_pthread.dylib             0x00007fff518cd3fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

libsystem_kernel.dylib`__pthread_kill:
    0x7fff518292bc <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x7fff518292c1 <+5>:  movq   %rcx, %r10
    0x7fff518292c4 <+8>:  syscall 
->  0x7fff518292c6 <+10>: jae    0x7fff518292d0            ; <+20>
    0x7fff518292c8 <+12>: movq   %rax, %rdi
    0x7fff518292cb <+15>: jmp    0x7fff51823457            ; cerror_nocancel
    0x7fff518292d0 <+20>: retq

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by CoderHenry66** [comment]
请看断言，WAAVSERotateCommand.m Line 19
