### ISSUE TITLE
视频添加图片水印太模糊了吧

### ISSUE THREAD

**Issue by IIIOS** [CoderHenry66/WAVideoBox#25]
左上角为加的水印图片。
<img width="889" alt="WechatIMG5728" src="https://user-images.githubusercontent.com/13568689/71879291-b9b18480-3168-11ea-84c8-bc1631510a7c.png">
_

**Comment by CoderHenry66** [comment]
demo里是不会的，贴代码和图片源文件，我五一看下，  287819129@qq.com
