### ISSUE TITLE
压缩体积不变化

### ISSUE THREAD

**Issue by jiangyuan0336** [CoderHenry66/WAVideoBox#3]
指定ratio为WAVideoExportRatio960x540，改变videoQuality的大小，输出的视频还是一样的，没有清晰度和体积变化

**Comment by jiangyuan0336** [comment]
可不可以出个这样的demo，就是指定WAVideoExportRatio960x540，然后通过去改变videoQuality的大小来改变不同的压缩比例呢？

**Comment by CoderHenry66** [comment]
不好意思，最近没时间上，
默认ratio为WAVideoExportRatio960x540,不需指定
videoQuality已修复
