### ISSUE TITLE
两个视频合并时添加转场可以实现吗？

### ISSUE THREAD

**Issue by glener** [CoderHenry66/WAVideoBox#4]
我看到现在2个视频合并是在一条视频轨道上的，苹果官方的demo用的是2个视频轨道来合并去实现添加转场效果，我尝试用2个视频轨道后发现如果视频尺寸不一致时，转场那部分进行缩放操作会和用于转场效果的transform操作有冲突。大神知道有什么办法解决吗？

**Comment by CoderHenry66** [comment]
两个不同size的视频做叠加，有可能本身就需要调整单个视频轨道的transform
如果你调整了transform，再用transform去做动画，就需要计算transform的叠加
