### ISSUE TITLE
建议用avassetwriter实现压缩,这样可以设置更细节的东西

### ISSUE THREAD

**Issue by a970891** [CoderHenry66/WAVideoBox#9]
比如比特率

**Comment by CoderHenry66** [comment]
谢谢建议，但个人觉得avassetwriter压缩速度太慢，用AVExport也可以做到精确的比特率，就是开启videoCompostion，限制文件的大小，也就是现在框架对外开放的量化的视频质量videoQuailty。如果不需要videoCompostion的情况下，AVExport的速度是writer无法比美的哦〜

**Comment by a970891** [comment]
感谢回复! 最近正在研究这块, AVExport的速度确实很好很强大, videoCompostion这块之前确实没有想到, 再次感谢!
